[package]
name = "genetic-lander-rust"
version = "0.1.0"
authors = ["Pedro Ramos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
json = "0.12.4"
